version: "3.7"
services:
  web:
    image: practic2
    build: .
    volumes:
      - ./ez-python-3.4-practice-2:/app
    ports:
      - 8888:8888
    networks:
      - practic2
    depends_on:
      - database
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mysecret"
    restart: always
    networks:
      - practic2
  nginx:
    image: nginx:1.21.1-alpine
    restart: unless-stopped
    volumes:
      - ./ci/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
    ports:
      - 8989:8989
    networks:
      - practic2
networks:
  practic2: {}
